# 由 agent（Kimi Code）按 abstract_structure_annotation_prompt.md（v0.2 冻结口径）
# 对 pilot_review_subset 25 篇做的独立审核参照标注。标注性质：agent 审核参照，不是 human gold。
# 标注时只读摘要原文与固定切句，未参考任何模型输出。
# 写入时由本脚本程序化校验：句子全覆盖、每条 quote 是对应句的精确非空子串、
# finding_focus / how_aspects 的 null 与空列表规则、connective_only 一致性、paper_type 证据匹配。
import json
from pathlib import Path

RUN = Path(__file__).resolve().parents[3] / "data/processed/abstract_structure/run_20260908_a"

A = []  # (article_id, paper_type, input_issues, per-sentence annotations, note)

def pt(primary, emp, the, st, evidence, note):
    return {"primary_type": primary, "empirical_component": emp,
            "theory_component": the, "structural_component": st,
            "evidence": [{"sentence_id": sid, "quote": q} for sid, q in evidence],
            "note": note}

def fn(label, quotes, focus=None, aspects=None):
    return {"label": label, "evidence": [
        {"quote": q, "finding_focus": focus if label == "findings" else None,
         "how_aspects": aspects if label == "how" else []} for q in quotes]}

def fnv(label, items):
    # items: list of (quote, focus_or_None, aspects_or_None)，用于同句同 label 的多条 evidence
    return {"label": label, "evidence": [
        {"quote": q, "finding_focus": fo if label == "findings" else None,
         "how_aspects": asp if label == "how" else []} for q, fo, asp in items]}

def other(q, desc):
    return {"quote": q, "function_description": desc}

def unc(q, cands, reason):
    return {"quote": q, "candidate_functions": cands, "reason": reason}

A.append(("AER:10.1257/aer.20161749",
  pt("theory", "no", "yes", "no",
     [(1, "this paper studies the equilibrium interaction")],
     "Equilibrium analysis of accounting measurement rules; no data or empirical analysis stated."),
  [],
  {1: {"functions": [fn("what", ["this paper studies the equilibrium interaction between the measurement rules that firms find privately optimal, firms' governance, and the liquidity in the secondary market for their assets"])],
       "other_content": [other("Building on the idea that accounting matters for corporate governance", "motivating premise about the topic's importance")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["an excessive use of market-value accounting: corporate performance measures rely excessively on the information generated by other firms' asset sales and insufficiently on the realization of a firm's own capital gains."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("findings", ["This dries up market liquidity and reduces the informativeness of price signals, thereby making it more costly for firms to overcome their agency problems."], focus="central"),
        fn("how", ["dries up market liquidity and reduces the informativeness of price signals"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "3 句理论摘要：S1 前提背景为 other；S3 机制链同为 findings 与 how[mechanism]。"))

A.append(("AER:10.1257/aer.20151272",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(3, "develop and estimate a quantitative model linking trade with the environment")],
     "Descriptive evidence plus an estimated quantitative trade-environment model."),
  [],
  {1: {"functions": [],
       "other_content": [other("Between 1990 and 2008, air pollution emissions from U.S. manufacturing fell by 60 percent despite a substantial increase in manufacturing output.", "stylized-fact background motivating the decomposition")],
       "uncertain_content": [
        unc("air pollution emissions from U.S. manufacturing fell by 60 percent despite a substantial increase in manufacturing output", ["findings", "other"],
            "the stylized fact may be the paper's own descriptive finding or prior-known background; the abstract does not attribute it")],
       "connective_only": False},
   2: {"functions": [fn("findings", ["these emissions reductions are primarily driven by within-product changes in emissions intensity rather than changes in output or in the composition of products produced"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("how", ["develop and estimate a quantitative model linking trade with the environment"], aspects=["model"]),
        fn("what", ["to better understand the economic forces driving these changes"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["the implicit pollution tax that manufacturers face doubled between 1990 and 2008"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["These changes in environmental regulation, rather than changes in productivity and trade, account for most of the emissions reductions."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 风格化事实的归属真实歧义（findings vs other），用 uncertain 表达。"))

A.append(("AER:10.1257/aer.20161441",
  pt("theory", "no", "yes", "no",
     [(4, "The paper identifies the constraints, opportunities, and trade-offs of persuading people to change worldview.")],
     "Non-Bayesian persuasion theory; no data stated."),
  [],
  {1: {"functions": [],
       "other_content": [other("Persuaders often face the task of changing their listeners' worldview, which may involve conveying evidence that disconfirms that view.", "background motivating the persuasion problem")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [],
       "other_content": [other("It has been shown, however, that people are often reluctant to change their worldviews.", "background finding attributed to prior work, not this paper")],
       "uncertain_content": [], "connective_only": False},
   3: {"functions": [],
       "other_content": [other("These aspects of persuasion cannot be captured in the standard Bayesian framework.", "limitation of the standard framework as research motivation")],
       "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("what", ["The paper identifies the constraints, opportunities, and trade-offs of persuading people to change worldview."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["necessary and sufficient conditions under which it is optimal for persuaders to do so"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [fn("findings", ["when and how they conceal disconfirming evidence and take advantage of their listener's existing worldview"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "前三句全为背景/动机（other），what 到 S4 才出现；S2 明确是在先研究结论，不记本文 findings。"))

A.append(("AER:10.1257/aer.20181219",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(4, "Structural estimation")],
     "Reduced-form forecast-error tests plus a structurally estimated diagnostic-expectations model."),
  [],
  {1: {"functions": [
        fn("what", ["We study the rationality of individual and consensus forecasts of macroeconomic and financial variables"]),
        fn("how", ["using the methodology of Coibion and Gorodnichenko (2015), who examine predictability of forecast errors from forecast revisions"], aspects=["other_method"])],
       "other_content": [other("Coibion and Gorodnichenko (2015)", "author-year citation of the source methodology")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["individual forecasters typically overreact to news, while consensus forecasts underreact relative to full-information rational expectations"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fnv("how", [
        ("a diagnostic expectations version of a dispersed information learning model", None, ["model"]),
        ("diagnostic expectations", None, ["mechanism"])])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [
        fn("how", ["Structural estimation"], aspects=["other_method"]),
        fnv("findings", [
            ("departures from Bayesian updating in the form of diagnostic overreaction capture important variation in forecast biases across different series", "central", None),
            ("yielding a belief distortion parameter similar to estimates obtained in other settings", "secondary", None)])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 方法引用嵌在 how 跨度内，作者-年份引用另记 other；S3 模型名与机制名分两个 how 跨度。"))

A.append(("AER:10.1257/aer.20220308",
  pt("mixed_or_structural", "unclear", "yes", "yes",
     [(5, "Calibrating the model")],
     "Fiscal theory with a calibrated quantitative application to the US and Japan; calibration is not necessarily analysis of observed data."),
  [],
  {1: {"functions": [
        fn("what", ["We develop a tractable framework for deficit and debt dynamics."]),
        fn("how", ["a tractable framework for deficit and debt dynamics"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["A \"free lunch\" fiscal deficit—one that raises spending without higher future taxes—is sustainable without zero lower bound (ZLB) only when R < G − φ, where φ is the sensitivity of the interest rate to the debt level."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("findings", ["both high and low deficits can increase debt, as the latter weaken demand and reduce nominal growth at the ZLB"], focus="secondary"),
        fn("how", ["the latter weaken demand and reduce nominal growth at the ZLB"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["A rise in income inequality expands fiscal space outside the ZLB, but contracts it at the ZLB."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [
        fn("how", ["Calibrating the model"], aspects=["model"]),
        fn("findings", ["little space for \"free lunch\" policies for the United States in 2019, but significant space for Japan"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "理论+校准；empirical_component 记 unclear（校准是否构成观测数据分析无法从摘要判定）。"))

A.append(("ECMA:10.3982/ecta11206",
  pt("theory", "no", "yes", "no",
     [(3, "We analyze the problem of existence and uniqueness of equilibrium values")],
     "Existence/uniqueness analysis of market-price-triggered contingent capital; formal theory only."),
  [],
  {1: {"functions": [fn("what", ["We analyze the internal consistency of using the market price of a firm's equity to trigger a contractual change in the firm's capital structure, given that the value of the equity itself depends on the firm's capital structure."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [],
       "other_content": [other("the case of contingent capital for banks, in the form of debt that converts to equity, when conversion is triggered by a decline in the bank's stock price", "application emphasized as of particular interest")],
       "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("what", ["We analyze the problem of existence and uniqueness of equilibrium values for a firm's liabilities in this context, meaning values consistent with a market-price trigger."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["Discrete-time dynamics allow multiple equilibria."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["the possibility of multiple equilibria can largely be ruled out in continuous time, where the price of the triggering security adjusts in anticipation of breaching the trigger"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [fn("findings", ["Our main condition for existence of an equilibrium requires that the consequences of triggering a conversion be consistent with the direction in which the trigger is crossed."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [
        fn("why_it_matters", ["For the design of contingent capital with a stock price trigger, this condition may be interpreted to mean that conversion should be disadvantageous to shareholders"]),
        fn("findings", ["it is satisfied by setting the trigger sufficiently high"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("findings", ["Uniqueness follows provided the trigger is sufficiently accessible by all candidate equilibria."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   9: {"functions": [fn("what", ["We illustrate precise formulations of these conditions with a variety of applications."])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S7 设计含义（why）与结果从句（findings）同句多标签；S2 应用背景记 other。"))

A.append(("ECMA:10.3982/ecta13117",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(4, "we perform an empirical analysis using data on the Second Congo War")],
     "Network theory of conflict combined with an empirical analysis; equilibrium estimates feed counterfactual policy evaluation."),
  [{"sentence_id": 5, "issue": "sentence fragment; enumeration continues in S6-S8 (segmentation artifact of the fixed sentence split)"}],
  {1: {"functions": [fn("what", ["We study from both a theoretical and an empirical perspective how a network of military alliances and enmities affects the intensity of a conflict."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("how", ["The model combines elements from network theory and from the politico-economic theory of conflict."], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["We obtain a closed-form characterization of the Nash equilibrium."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fnv("how", [
        ("Using the equilibrium conditions", None, ["model"]),
        ("we perform an empirical analysis using data on the Second Congo War, a conflict that involves many groups in a complex network of informal alliances and rivalries", None, ["data"])])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("what", ["The estimates of the fighting externalities are then used to infer the extent to which the conflict intensity can be reduced through"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [],
       "other_content": [other("(i) dismantling specific fighting groups involved in the conflict;", "list item: counterfactual intervention under evaluation")],
       "uncertain_content": [], "connective_only": False},
   7: {"functions": [],
       "other_content": [other("(ii) weapon embargoes;", "list item: counterfactual intervention under evaluation")],
       "uncertain_content": [], "connective_only": False},
   8: {"functions": [],
       "other_content": [other("(iii) interventions aimed at pacifying animosity among groups.", "list item: counterfactual intervention under evaluation")],
       "uncertain_content": [], "connective_only": False},
   9: {"functions": [
        fn("what", ["we study how policy shocks can induce a reshaping of the network structure"]),
        fn("how", ["with the aid of a random utility model"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "固定切句把 S5-S8 拆成句首+三个列表项：S5 记 input_issues，列表项记 other（有实质内容但无命题）。"))

A.append(("ECMA:10.3982/ecta17536",
  pt("theory", "no", "yes", "no",
     [(1, "What incentives do governments have to negotiate trade agreements that constrain their domestic regulatory policies?")],
     "Model-based analysis of trade agreements over regulatory policies; no data stated."),
  [],
  {1: {"functions": [fn("what", ["What incentives do governments have to negotiate trade agreements that constrain their domestic regulatory policies?"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("how", ["a model in which firms design products to appeal to local consumer tastes, but their fixed costs increase with the difference between versions of their product destined for different markets"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["firms' profit-maximizing choices of product attributes are globally optimal in the absence of consumption externalities, but national governments have unilateral incentives to invoke regulatory protectionism to induce firm delocation"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["An efficient trade agreement requires commitments not to engage in such opportunistic behavior."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["A rule requiring mutual recognition of standards can be used to achieve efficiency, but one that requires only national treatment falls short."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [fn("findings", ["When product attributes confer local consumption externalities, an efficient trade agreement must coordinate the fine details of countries' regulatory policies."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 为显式研究问句（what）；S2 整句是模型设定，what 已由 S1 承担，不再重复标。"))

A.append(("ECMA:10.3982/ecta16699",
  pt("mixed_or_structural", "yes", "yes", "no",
     [(7, "We propose a dynamic location model"),
      (8, "using French individual panel data from tax returns")],
     "Conceptual location-asset theory combined with descriptive panel-data evidence; the model is not estimated structurally in the abstract."),
  [],
  {1: {"functions": [],
       "other_content": [other("The location of individuals determines their job and schooling opportunities, amenities, and housing costs.", "topic background motivating the location-choice analysis")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("what", ["We conceptualize the location choice of individuals as a decision to invest in a “location asset.”"]),
        fn("how", ["a decision to invest in a “location asset.”"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("how", ["This asset has a current cost equal to the location's rent, and a future payoff through better job and schooling opportunities."], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["savers in the location asset transfer resources into the future by going to expensive locations with high future returns"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["borrowers transfer resources to the present by going to cheap locations that offer few other advantages"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [
        fn("findings", ["Holdings of the location asset depend on its comparison to other assets"], focus="secondary"),
        fn("how", ["the location asset is not subject to borrowing constraints"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [
        fn("what", ["We propose a dynamic location model and derive an agent's mobility choices after experiencing income shocks."]),
        fn("how", ["a dynamic location model"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [
        fn("findings", ["We document the investment dimension of location and confirm the core predictions of our theory"], focus="central"),
        fn("how", ["using French individual panel data from tax returns"], aspects=["data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "概念框架（S2-S6）+实证确认（S8）；structural_component 记 no（摘要未显示结构估计）。"))

A.append(("ECMA:10.3982/ecta21402",
  pt("theory", "no", "yes", "no",
     [(1, "This paper introduces and analyzes sequentially stable outcomes in extensive-form games.")],
     "New solution concept for extensive-form games with formal properties; pure theory."),
  [],
  {1: {"functions": [fn("what", ["This paper introduces and analyzes sequentially stable outcomes in extensive-form games."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [],
       "other_content": [other("An outcome ω is sequentially stable if, for any ε > 0 and any small enough perturbation of the players' behavior, there is an ε -perturbation of the players' payoffs and a corresponding equilibrium with outcome close to ω .", "formal definition of the introduced solution concept")],
       "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["Sequentially stable outcomes exist for all finite games and are outcomes of sequential equilibria."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["They are closely related to stable sets of equilibria and satisfy versions of forward induction, iterated strict equilibrium dominance, and invariance to simultaneous moves."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["In signaling games, sequentially stable outcomes pass the standard selection criteria, and when payoffs are generic, they coincide with outcomes of stable sets of equilibria."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S2 形式定义记 other（明确功能在四标签之外），不是 how——定义的是新概念而非论文的方法。"))

A.append(("JPE:10.1086/696280",
  pt("mixed_or_structural", "no", "yes", "yes",
     [(3, "Quantitatively, this policy reduces sharply the frequency and magnitude of crises")],
     "Time-consistent policy theory evaluated quantitatively ('Quantitatively, ...'); no observed-data analysis stated."),
  [],
  {1: {"functions": [],
       "other_content": [other("Collateral constraints widely used in models of financial crises feature a pecuniary externality: Agents do not internalize how borrowing decisions made in “good times” affect collateral prices during a crisis.", "established friction in existing crisis models, used as motivation")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("findings", ["under commitment the optimal financial regulator’s plans are time inconsistent"], focus="central"),
        fn("what", ["study time-consistent policy"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["this policy reduces sharply the frequency and magnitude of crises, removes fat tails from the distribution of asset returns, and increases social welfare"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["constant debt taxes are ineffective and can be welfare reducing, while an optimized “macroprudential Taylor rule” is effective but less so than the optimal time-consistent policy"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 是已有模型中的已知摩擦（other，非本文 findings）；类型判 mixed_or_structural 依据 Quantitatively 量化评估，emp=no。"))

A.append(("JPE:10.1086/705553",
  pt("methods", "yes", "yes", "no",
     [(2, "We present a method to quantify the efficiency costs"),
      (4, "four empirical applications")],
     "Main contribution is a measurement method based on regression statistics, with a formal validity result and empirical illustrations."),
  [],
  {1: {"functions": [],
       "other_content": [other("Corrective taxes can solve many market failures, but actual policies frequently deviate from the theoretical ideal because of administrative or political constraints.", "topic background motivating the measurement problem")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("what", ["We present a method to quantify the efficiency costs of constraints on externality-correcting policies or, more generally, the costs of imperfect pricing"]),
        fn("how", ["using simple regression statistics"], aspects=["other_method"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["the R 2 and the sum of squared residuals from a regression of true externalities on policy variables measure relative welfare gains from policies"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("what", ["We illustrate via four empirical applications: random mismeasurement of externalities, imperfect electricity pricing, heterogeneity in the longevity of energy-consuming durable goods, and imperfect spatial policy differentiation."])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "方法论文：S3 形式性质为 central finding；S4 应用列举并入 what 任务声明，empirical_component 据此记 yes。"))

A.append(("JPE:10.1086/722935",
  pt("theory", "no", "yes", "no",
     [(1, "the existence of competitive equilibrium fundamentally depends on agents’ substitution effects, not their income effects")],
     "Formal equilibrium-existence duality results; pure theory."),
  [],
  {1: {"functions": [fn("findings", ["with indivisible goods, the existence of competitive equilibrium fundamentally depends on agents’ substitution effects, not their income effects"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["Our equilibrium existence duality allows us to transport results on the existence of competitive equilibrium from settings with transferable utility to settings with income effects."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["net substitutability—which is a strictly weaker condition than gross substitutability—is sufficient for the existence of competitive equilibrium"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["Further applications give new existence results beyond the case of (net) substitutes."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("why_it_matters", ["Our results have implications for auction design."])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "只有结论开头（S1 即 central finding），无独立 what 句；S5 为明确的应用意义句。"))

A.append(("JPE:10.1086/725174",
  pt("empirical", "yes", "yes", "no",
     [(1, "We use laboratory experiments")],
     "Laboratory-experiment tests of rational inattention models; a generalized model is fit but no structural estimation is stated."),
  [],
  {1: {"functions": [
        fn("what", ["to test models of rational inattention"]),
        fnv("how", [
            ("We use laboratory experiments", None, ["design"]),
            ("models of rational inattention, in which people acquire information to maximize utility net of information costs", None, ["model"])])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["subjects adjust their attention in response to changes in incentives, in line with the rational inattention model"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["our results are qualitatively inconsistent with information costs that are linear in Shannon entropy"], focus="central")],
       "other_content": [other("as is often assumed in applied work", "reference to common practice in applied work")],
       "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["Our data are best fit by a generalization of the Shannon model, which allows for a more flexible response to incentives and for some states of the world to be harder to distinguish than others."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "实验检验为主；S3 从句对应用文献惯例的提及记 other。"))

A.append(("JPE:10.1086/729447",
  pt("empirical", "yes", "no", "no",
     [(2, "We study 30 US cities that ran 73 RCTs with a national nudge unit.")],
     "Observational analysis of city adoption decisions across 73 RCTs."),
  [],
  {1: {"functions": [],
       "other_content": [
        other("Governments increasingly use randomized controlled trials (RCTs) to test innovations", "topic background"),
        other("we know little about how they incorporate results into policymaking", "research gap statement")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("what", ["We study 30 US cities that ran 73 RCTs with a national nudge unit."]),
        fn("how", ["30 US cities that ran 73 RCTs with a national nudge unit"], aspects=["data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["Cities adopt a nudge treatment into their communications in 27% of the cases."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["the strength of the evidence and key city features do not strongly predict adoption; instead, the largest predictor is whether the RCT was implemented using preexisting communication, as opposed to new communication"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [
        fn("findings", ["We identify organizational inertia as a leading explanation"], focus="central"),
        fn("how", ["changes to preexisting infrastructure are more naturally folded into subsequent processes"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 背景+缺口（other）；S5 识别出的解释机制同为 findings 与 how[mechanism]。"))

A.append(("QJE:10.1093/qje/qjw006",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(1, "We propose a theory linking imperfect information to resource misallocation"),
      (3, "a novel empirical strategy that uses a combination of firm-level production and stock market data")],
     "Theory of information-driven misallocation plus an empirical strategy that pins down the information structure and quantifies losses."),
  [],
  {1: {"functions": [
        fn("what", ["We propose a theory linking imperfect information to resource misallocation and hence to aggregate productivity and output."]),
        fn("how", ["linking imperfect information to resource misallocation and hence to aggregate productivity and output"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("how", ["firms look to a variety of noisy information sources when making input decisions"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("how", ["a novel empirical strategy that uses a combination of firm-level production and stock market data to pin down the information structure in the economy"], aspects=["design", "data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [
        fn("how", ["applying this methodology to data from the United States, China, and India"], aspects=["data"]),
        fn("findings", ["reveals substantial losses in productivity and output due to the informational friction"], focus="central")],
       "other_content": [other("Even when only capital is chosen under imperfect information", "scope condition of the quantitative exercise")],
       "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["Our estimates for these losses range from 7% to 10% for productivity and 10% to 14% for output in China and India, and are smaller, though still significant, in the United States."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [fn("findings", ["Losses are substantially higher when labor decisions are also made under imperfect information."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [fn("findings", ["firms turn primarily to internal sources for information; learning from financial markets contributes little, even in the United States"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 任务声明中的机制链记 how[mechanism]；S4 范围限定从句保留为 other。"))

A.append(("QJE:10.1093/qje/qjx035",
  pt("empirical", "yes", "no", "no",
     [(1, "We use a hypothetical choice methodology to estimate preferences for workplace attributes")],
     "Stated-preference estimation from a student sample plus a follow-up survey; no structural model."),
  [],
  {1: {"functions": [
        fn("what", ["to estimate preferences for workplace attributes"]),
        fnv("how", [
            ("a hypothetical choice methodology", None, ["design"]),
            ("a sample of high-ability undergraduates attending a highly selective university", None, ["data"])])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["women on average have a higher willingness to pay (WTP) for jobs with greater work flexibility and job stability, and men have a higher WTP for jobs with higher earnings growth"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("findings", ["These job preferences relate to college major choices and to actual job choices reported in a follow-up survey four years after graduation."], focus="secondary"),
        fn("how", ["a follow-up survey four years after graduation"], aspects=["data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["The gender differences in preferences explain at least a quarter of the early career gender wage gap."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S3 结果句内的随访调查信息另记 how[data]（独立跨度）。"))

A.append(("QJE:10.1093/qje/qjy009",
  pt("theory", "no", "yes", "no",
     [(1, "this article characterizes the socially efficient organization of the market with search frictions")],
     "Welfare analysis of market organization under search frictions; pure theory."),
  [],
  {1: {"functions": [fn("what", ["this article characterizes the socially efficient organization of the market with search frictions"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("findings", ["The efficient organization depends on the relative elasticity in the supply between the two sides of the market, the costs of participating in the market and organizing trade, and the (a)symmetry in matching."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["the social optimum can be implemented by a realistic market equilibrium where the organizers set up trading sites to direct the other side’s search"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("why_it_matters", ["The results provide a unified explanation for why trade has often been organized by sellers in the goods market, by buyers (firms) in the labor market, and by both sides in the asset market."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("why_it_matters", ["The analysis also sheds light on how the efficient market organization can change with innovations such as e-commerce and just-in-time production."])],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S4/S5 显式把结果用于解释现实组织形态与创新情景，记 why_it_matters 而非 findings。"))

A.append(("QJE:10.1093/qje/qjaf015",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(2, "we calibrate a standard macro model with the estimated micro MPCs"),
      (6, "using the CEX data")],
     "Calibrated macro model combined with CEX-based bias-corrected MPC estimates."),
  [],
  {1: {"functions": [fn("findings", ["the high estimated marginal propensities to consume (MPCs) from the leading household studies result in implausible macroeconomic counterfactuals"], focus="central")],
       "other_content": [], "uncertain_content": [
        unc("We present evidence that the high estimated marginal propensities to consume (MPCs) from the leading household studies result in implausible macroeconomic counterfactuals.", ["what", "findings"],
            "main-answer announcement; narrow what excludes it, inclusive What counts the central finding sentence")],
       "connective_only": False},
   2: {"functions": [
        fnv("how", [
            ("Using the 2008 tax rebate as a case study", None, ["design"]),
            ("we calibrate a standard macro model with the estimated micro MPCs", None, ["model"])]),
        fn("what", ["to construct counterfactual macroeconomic consumption paths in the absence of a rebate"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["consumption expenditures would have plummeted in spring and summer 2008 and mostly recovered in September 2008"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [
        fn("how", ["We use narratives and forecasts"], aspects=["data"]),
        fn("findings", ["these paths are implausible"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["standard two-way fixed effect estimates of the micro MPCs are upward biased"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [
        fn("findings", ["we estimate smaller micro MPCs using the CEX data than the previous literature"], focus="secondary"),
        fn("how", ["using the CEX data"], aspects=["data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [fn("findings", ["realistic modifications of the model result in general equilibrium forces that dampen rather than amplify micro MPCs"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("findings", ["The combination of smaller micro MPCs and dampening general equilibrium forces implies general equilibrium consumption multipliers that are below 0.2."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S1 为 narrow/inclusive What 分歧的标准例（findings + uncertain[what]）；S4 叙事与预测作为证据来源记 how[data]。"))

A.append(("QJE:10.1093/qje/qjaf047",
  pt("empirical", "yes", "no", "no",
     [(1, "We construct the first annual market rent and home sales price series for American cities over the twentieth century")],
     "Newly constructed long-run rent and price series with descriptive findings."),
  [],
  {1: {"functions": [
        fn("what", ["We construct the first annual market rent and home sales price series for American cities over the twentieth century"]),
        fn("how", ["using 2.7 million newspaper real estate listings"], aspects=["data"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [],
       "other_content": [], "uncertain_content": [
        unc("Our findings revise several stylized facts about U.S. housing markets.", ["why_it_matters", "other"],
            "significance announcement pointing at understanding, but no specific consequence or use is drawn out")],
       "connective_only": False},
   3: {"functions": [fn("findings", ["Real market rents did not fall during the postwar period in most cities and rose nationally by 60% from 1890 to 2006."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["We also document higher sales price growth between 1953 and 1987 relative to previous series."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["Real prices reached almost four times their 1890 level by 2006."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [fn("findings", ["Prices grew most in metros with high demand and low levels of construction."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [fn("findings", ["the rent-to-price ratio fell from about 8% in the early twentieth century to 3% by 2006, consistent with declines in the cost of owning housing relative to renting"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("findings", ["the annual return to owning housing was 9%, driven mostly by rental returns of 7.7%, with capital gains contributing only 1.3%"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   9: {"functions": [fn("findings", ["While capital gains were close to zero from 1890 to 1940, they grew to nearly a third of total returns from 1970 to 2006."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "新数据构建论文；S2 为无具体内容的意义宣示，按真实歧义记 uncertain（why vs other）。"))

A.append(("REStud:10.1093/restud/rdx029",
  pt("theory", "no", "yes", "no",
     [(1, "We introduce learning into an otherwise standard two-sided search-and-bargaining market.")],
     "Search-and-bargaining model with learning; equilibrium results only, no data."),
  [],
  {1: {"functions": [
        fn("what", ["We introduce learning into an otherwise standard two-sided search-and-bargaining market."]),
        fn("how", ["an otherwise standard two-sided search-and-bargaining market"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("how", ["There is uncertainty about the price distribution due to uncertainty about an underlying exogenous state of relative demand: in the high state, buyers are on the long side; otherwise, they are on the short side."], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["In equilibrium, prices are on average higher in the high state."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("how", ["Individual agents learn about the distribution while searching."], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("findings", ["Agents typically start out by experimenting with a tough bargaining position—buyers may initially insist on a low price and sellers on a high price."], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [
        fn("findings", ["After successive failures to trade, agents become increasingly pessimistic about the market conditions and soften their bargaining stance."], focus="secondary"),
        fn("how", ["agents become increasingly pessimistic about the market conditions and soften their bargaining stance"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [fn("findings", ["When frictions are small, equilibrium transaction prices are approximately market clearing, despite aggregate demand being unknown."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("why_it_matters", ["the search-and-bargaining procedure enables price discovery in a decentralized market"])],
       "other_content": [], "uncertain_content": [
        unc("the search-and-bargaining procedure enables price discovery in a decentralized market", ["findings", "why_it_matters"],
            "concluding sentence restates the result's meaning; may also be read as a restated finding rather than an implication beyond the result")],
       "connective_only": False}},
  "S2/S4 为模型环境与学习机制（how）；S8 结尾句在 findings 重述与 why 之间真实歧义，主标 why + uncertain。"))

A.append(("REStud:10.1093/restud/rdx082",
  pt("mixed_or_structural", "yes", "yes", "yes",
     [(4, "our calibrated model"),
      (2, "Using U.S. regional and industry data")],
     "Calibrated spatial model used for counterfactuals, with elasticities obtained from U.S. regional and industry data."),
  [],
  {1: {"functions": [fn("what", ["We study the impact of intersectoral and interregional trade linkages in propagating disaggregated productivity changes to the rest of the economy."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("how", ["Using U.S. regional and industry data"], aspects=["data"]),
        fn("what", ["we obtain the aggregate, regional and sectoral elasticities of measured total factor productivity, GDP, and employment to regional and sectoral productivity changes"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["the elasticities vary significantly depending on the sectors and regions affected, and are importantly determined by the spatial structure of the economy"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [
        fn("what", ["We use our calibrated model to perform a variety of counterfactual exercises including several specific studies of the aggregate and disaggregate effects of shocks to productivity and infrastructure"]),
        fn("how", ["our calibrated model"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [],
       "other_content": [other("the boom in California’s computer industry, the productivity boom in North Dakota associated with the shale oil boom, the disruptions in New York’s finance and real state industries during the 2008 crisis, as well as the effect of the destruction of infrastructure in Louisiana following hurricane Katrina", "enumeration of specific historical episodes analyzed")],
       "uncertain_content": [], "connective_only": False}},
  "S5 情景枚举记 other；S4 反事实练习任务与校准模型分标 what/how。"))

A.append(("REStud:10.1093/restud/rdy054",
  pt("empirical", "yes", "yes", "no",
     [(5, "an experiment in which we randomly manipulate the thirst of participants"),
      (6, "using data from thousands of amusement park visitors")],
     "A simple framework plus two empirical tests (RCT and observational data); tests are the main contribution."),
  [],
  {1: {"functions": [],
       "other_content": [other("When judging the value of a good, people may be overly influenced by the state in which they previously consumed it.", "motivating claim describing the hypothesized attribution bias")],
       "uncertain_content": [], "connective_only": False},
   2: {"functions": [],
       "other_content": [other("someone who tries out a new restaurant while very hungry may subsequently rate it as high quality, even if the food is mediocre", "illustrative example of the hypothesized bias")],
       "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("what", ["We produce a simple framework for this form of attribution bias that embeds a standard model of decision making as a special case."]),
        fn("how", ["a simple framework for this form of attribution bias that embeds a standard model of decision making as a special case"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("what", ["We test for attribution bias across two consumer decisions."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   5: {"functions": [fn("how", ["an experiment in which we randomly manipulate the thirst of participants prior to consuming a new drink"], aspects=["design"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [
        fn("how", ["using data from thousands of amusement park visitors"], aspects=["data"]),
        fn("what", ["we explore how pleasant weather during their most recent trip affects their stated and actual likelihood of returning"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [fn("findings", ["people misattribute the influence of a temporary state to a stable quality of the consumption good"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("findings", ["We provide evidence against several alternative accounts for our findings"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S8 后从句 'discuss the broader implications...' 为无内容的讨论预告，按规则不占跨度、句不记 connective_only（句内有实质内容）。"))

A.append(("REStud:10.1093/restud/rdad009",
  pt("empirical", "yes", "no", "no",
     [(2, "Using commuting zone level variation in exposure")],
     "Shift-share style exposure variation estimates of import competition effects."),
  [],
  {1: {"functions": [fn("what", ["We assess the impact of a rapid rise in Japanese import competition on the growth in racial earnings and employment gaps during the 1970s and 80s."])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [
        fn("how", ["Using commuting zone level variation in exposure"], aspects=["design"]),
        fn("findings", ["Japanese competition led to a decrease in manufacturing employment and labour force participation for blacks"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [
        fn("findings", ["This was driven by a shift in demand for skill in manufacturing."], focus="secondary"),
        fn("how", ["a shift in demand for skill in manufacturing"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [fn("findings", ["The difference in effects between the 10th percentile most and least exposed commuting zone was equivalent to 36–46% of the relative rise in black non-labour force participation, and 78–96% of the relative decline in black median male earnings."], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S3 机制归因句同为 findings 与 how[mechanism]。"))

A.append(("REStud:10.1093/restud/rdaf061",
  pt("mixed_or_structural", "no", "yes", "yes",
     [(1, "I quantitatively analyse the macroeconomic impacts of raising capital requirements in a model")],
     "Quantitative (calibrated) banking model with heterogeneous firms and banks; no observed-data analysis stated in the abstract."),
  [],
  {1: {"functions": [
        fn("what", ["I quantitatively analyse the macroeconomic impacts of raising capital requirements"]),
        fn("how", ["in a model in which heterogeneous firms may choose either intermediated or direct finance"], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   2: {"functions": [fn("how", ["Heterogeneous banks compete with other banks and the bond market, fund loans with insured deposits and costly equity (subject to a minimum capital-to-asset ratio), and monitor borrowers."], aspects=["model"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   3: {"functions": [fn("findings", ["tighter capital requirements reduce costly bank failures while having only small effects on key macroeconomic aggregates",
                                      "raising capital requirements above current levels can be welfare-improving"], focus="central")],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   4: {"functions": [], "other_content": [], "uncertain_content": [], "connective_only": True},
   5: {"functions": [
        fn("findings", ["even though banks cut loan supply for a given level of net worth under a tighter capital requirement, in equilibrium banks’ net worth rises to dampen this effect"], focus="secondary"),
        fn("how", ["in equilibrium banks’ net worth rises to dampen this effect"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   6: {"functions": [
        fn("findings", ["intense competition from the non-bank sector disciplines banks’ lending responses to tighter regulation"], focus="secondary"),
        fn("how", ["intense competition from the non-bank sector disciplines banks’ lending responses to tighter regulation"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   7: {"functions": [
        fn("findings", ["substitution by corporate firms offsets much of the decline in debt financing associated with tighter bank loan supply"], focus="secondary"),
        fn("how", ["substitution by corporate firms offsets much of the decline in debt financing associated with tighter bank loan supply"], aspects=["mechanism"])],
       "other_content": [], "uncertain_content": [], "connective_only": False},
   8: {"functions": [fn("findings", ["almost all of the modest costs associated with tighter capital requirements are concentrated within the bank-dependent non-corporate sector"], focus="secondary")],
       "other_content": [], "uncertain_content": [], "connective_only": False}},
  "S4 'Three main forces give rise to these results.' 为无内容预告 → connective_only；S5-S7 三个力量同为 findings 与 how[mechanism]。"))

# ---- 写出并自检 ----
subset_ids = [json.loads(l)["article_id"]
              for l in (RUN / "pilot_review_subset.jsonl").open(encoding="utf-8")]
corpus = {}
with (RUN / "corpus_manifest.jsonl").open(encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        if r["article_id"] in subset_ids:
            corpus[r["article_id"]] = r
assert set(corpus) == set(subset_ids), "corpus_manifest 缺少 subset 文章"
assert {a[0] for a in A} == set(subset_ids), "标注未覆盖 subset 全部 25 篇"

ALLOWED_LABELS = {"what", "how", "findings", "why_it_matters"}
ALLOWED_ASPECTS = {"data", "design", "model", "mechanism", "other_method"}

out = RUN / "review_agent_annotations.jsonl"
n_quotes = 0
with out.open("w", encoding="utf-8") as f:
    for article_id, paper_type, input_issues, sents, note in A:
        manifest = corpus[article_id]
        sents_by_id = {s["sentence_id"]: s["text"] for s in manifest["sentences"]}
        assert set(sents) == set(sents_by_id), f"{article_id}: 未覆盖全部句子"
        for ev in paper_type["evidence"]:
            assert ev["sentence_id"] in sents_by_id, f"{article_id}: 类型证据句 ID 不存在"
            assert ev["quote"] and ev["quote"] in sents_by_id[ev["sentence_id"]], \
                f"{article_id}: 类型证据 quote 不在句中"
            n_quotes += 1
        if paper_type["primary_type"] != "unclear":
            assert paper_type["evidence"], f"{article_id}: 非 unclear 类型缺证据"
        for sid, ann in sents.items():
            text = sents_by_id[sid]
            seen_labels = set()
            for func in ann["functions"]:
                assert func["label"] in ALLOWED_LABELS
                assert func["label"] not in seen_labels, f"{article_id} S{sid}: 同句重复 label {func['label']}"
                seen_labels.add(func["label"])
                assert func["evidence"], f"{article_id} S{sid}: {func['label']} 缺 evidence"
                for ev in func["evidence"]:
                    assert ev["quote"] and ev["quote"] in text, \
                        f"{article_id} S{sid} quote 不在句中: {ev['quote'][:60]}"
                    n_quotes += 1
                    if func["label"] == "findings":
                        assert ev["finding_focus"] in ("central", "secondary", "unclear")
                        assert ev["how_aspects"] == []
                    elif func["label"] == "how":
                        assert ev["finding_focus"] is None
                        assert ev["how_aspects"], f"{article_id} S{sid} how 缺 aspects"
                        assert len(set(ev["how_aspects"])) == len(ev["how_aspects"])
                        assert set(ev["how_aspects"]) <= ALLOWED_ASPECTS
                    else:
                        assert ev["finding_focus"] is None and ev["how_aspects"] == []
            for item in ann["other_content"]:
                assert item["quote"] and item["quote"] in text, \
                    f"{article_id} S{sid} other quote 不在句中"
                assert item["function_description"]
                n_quotes += 1
            for item in ann["uncertain_content"]:
                assert item["quote"] and item["quote"] in text, \
                    f"{article_id} S{sid} uncertain quote 不在句中"
                assert item["candidate_functions"] and item["reason"]
                assert set(item["candidate_functions"]) <= ALLOWED_LABELS | {"other"}
                n_quotes += 1
            if ann["connective_only"]:
                assert not ann["functions"] and not ann["other_content"] and not ann["uncertain_content"], \
                    f"{article_id} S{sid}: connective_only=true 但标注非空"
            else:
                assert ann["functions"] or ann["other_content"] or ann["uncertain_content"], \
                    f"{article_id} S{sid}: connective_only=false 但无任何标注"
        f.write(json.dumps({
            "schema_version": "abstract_structure_v0.1",
            "article_id": article_id,
            "annotator": "agent_kimi_code_review",
            "round": "pilot_review_subset",
            "label_basis": "abstract_only",
            "input_issues": input_issues,
            "paper_type": paper_type,
            "sentence_annotations": [{"sentence_id": sid, **sents[sid]} for sid in sorted(sents)],
            "annotator_note": note,
        }, ensure_ascii=False) + "\n")

# ---- 统计 ----
func_present = {k: 0 for k in ["what", "how", "findings", "why_it_matters"]}
n_other = n_unc = n_conn = n_focus_c = n_focus_s = 0
type_counts = {}
for article_id, paper_type, _, sents, _ in A:
    labels = {fn_["label"] for ann in sents.values() for fn_ in ann["functions"]}
    for lab in labels:
        func_present[lab] += 1
    if any(ann["other_content"] for ann in sents.values()):
        n_other += 1
    if any(ann["uncertain_content"] for ann in sents.values()):
        n_unc += 1
    n_conn += sum(1 for ann in sents.values() if ann["connective_only"])
    for ann in sents.values():
        for fn_ in ann["functions"]:
            if fn_["label"] == "findings":
                for ev in fn_["evidence"]:
                    if ev["finding_focus"] == "central":
                        n_focus_c += 1
                    elif ev["finding_focus"] == "secondary":
                        n_focus_s += 1
    type_counts[paper_type["primary_type"]] = type_counts.get(paper_type["primary_type"], 0) + 1

print(f"written {len(A)} annotations, {n_quotes} evidence quotes, all quotes verified as exact substrings")
print(f"function presence (papers of 25): {func_present}")
print(f"papers with other_content: {n_other}; papers with uncertain_content: {n_unc}")
print(f"connective_only sentences: {n_conn}")
print(f"finding_focus: central={n_focus_c}, secondary={n_focus_s}")
print(f"primary_type counts: {type_counts}")
